import type { QuestionDefinition } from './types';

export const DIGITAL_CHECK_QUESTIONS: QuestionDefinition[] = [
  {
    key: 'lead_sources',
    step: 1,
    type: 'multiple',
    question: 'Como novos clientes chegam até sua empresa?',
    description: 'Selecione todos os canais que trazem contatos hoje.',
    hasOther: true,
    otherPlaceholder: 'Qual outro canal?',
    options: [
      { value: 'whatsapp', label: 'WhatsApp' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'google', label: 'Google' },
      { value: 'website', label: 'Site' },
      { value: 'referral', label: 'Indicação' },
      { value: 'paid_ads', label: 'Tráfego pago' },
      { value: 'outbound', label: 'Prospecção ativa' },
      { value: 'physical_store', label: 'Loja / espaço físico' },
      { value: 'events', label: 'Eventos' },
      { value: 'other', label: 'Outro' },
    ],
  },
  {
    key: 'lead_handling',
    step: 2,
    type: 'multiple',
    question: 'Quando alguém demonstra interesse, o que acontece?',
    description: 'Como é o primeiro contato do momento em que o lead chega.',
    hasOther: true,
    otherPlaceholder: 'Descreva brevemente',
    options: [
      { value: 'manual_reply', label: 'Alguém responde manualmente' },
      { value: 'goes_to_whatsapp', label: 'O contato vai para o WhatsApp' },
      { value: 'auto_crm', label: 'O lead entra automaticamente em um CRM' },
      { value: 'auto_reply', label: 'Existe resposta automática' },
      { value: 'manual_distribute', label: 'Alguém distribui o lead manualmente' },
      { value: 'depends_available', label: 'Depende de quem estiver disponível' },
      { value: 'no_process', label: 'Não existe um processo definido' },
      { value: 'other', label: 'Outro' },
    ],
  },
  {
    key: 'lead_organization',
    step: 3,
    type: 'single',
    question: 'Onde suas oportunidades ficam organizadas?',
    description: 'O lugar oficial onde a equipe consulta o histórico das negociações.',
    options: [
      { value: 'crm', label: 'CRM' },
      { value: 'spreadsheet', label: 'Planilha' },
      { value: 'whatsapp', label: 'WhatsApp' },
      { value: 'calendar', label: 'Agenda' },
      { value: 'custom_system', label: 'Sistema próprio' },
      { value: 'paper', label: 'Papel' },
      { value: 'memory', label: 'Memória da equipe', nexNote: 'memória não é CRM.' },
      { value: 'no_place', label: 'Não temos um lugar definido' },
      { value: 'unknown', label: 'Não sei' },
    ],
  },
  {
    key: 'follow_up',
    step: 4,
    type: 'single',
    question: 'Se um potencial cliente não responder hoje, alguém lembra de falar com ele depois?',
    description: 'A consistência do acompanhamento comercial.',
    options: [
      { value: 'auto', label: 'Sim, automaticamente' },
      { value: 'crm_alert', label: 'Sim, pelo CRM' },
      { value: 'manual_track', label: 'Alguém acompanha manualmente' },
      { value: 'sometimes', label: 'Às vezes' },
      { value: 'usually_not', label: 'Normalmente não' },
      { value: 'no_follow_up', label: 'Não existe follow-up definido' },
    ],
  },
  {
    key: 'manual_tasks',
    step: 5,
    type: 'multiple',
    question: 'O que sua equipe repete manualmente toda semana?',
    description: 'Tarefas operacionais que tomam horas recorrentes do time.',
    hasOther: true,
    otherPlaceholder: 'Outra tarefa repetitiva',
    options: [
      { value: 'copy_paste', label: 'Copiar informações' },
      { value: 'register_leads', label: 'Cadastrar leads' },
      { value: 'send_messages', label: 'Enviar mensagens' },
      { value: 'follow_up_manual', label: 'Fazer follow-up' },
      { value: 'scheduling', label: 'Agendar' },
      { value: 'confirm_appointments', label: 'Confirmar agendamentos' },
      { value: 'proposals', label: 'Gerar propostas' },
      { value: 'quotes', label: 'Gerar orçamentos' },
      { value: 'invoicing', label: 'Cobrar clientes' },
      { value: 'update_sheets', label: 'Atualizar planilhas' },
      { value: 'reports', label: 'Produzir relatórios' },
      { value: 'faq_reply', label: 'Responder perguntas recorrentes' },
      { value: 'data_transfer', label: 'Transferir dados entre sistemas' },
      { value: 'none', label: 'Nenhuma dessas' },
      { value: 'other', label: 'Outro' },
    ],
  },
  {
    key: 'system_integration',
    step: 6,
    type: 'single',
    question: 'Suas ferramentas conversam entre si?',
    context: 'Por exemplo: site → WhatsApp → CRM → agenda → financeiro.',
    options: [
      { value: 'most_integrated', label: 'Sim, a maior parte é integrada' },
      { value: 'some_integrated', label: 'Algumas coisas são integradas' },
      { value: 'mostly_manual', label: 'Quase tudo depende de trabalho manual' },
      { value: 'isolated_islands', label: 'Cada sistema funciona separado' },
      { value: 'few_systems', label: 'Não utilizamos muitos sistemas' },
      { value: 'unknown', label: 'Não sei' },
    ],
  },
  {
    key: 'website_function',
    step: 7,
    type: 'multiple',
    question: 'Hoje seu site participa de verdade da operação?',
    description: 'Como a presença digital atua na rotina comercial.',
    options: [
      { value: 'no_website', label: 'Não temos site' },
      { value: 'presentation_only', label: 'Apenas apresenta a empresa' },
      { value: 'receives_contact', label: 'Recebe contatos' },
      { value: 'lead_capture', label: 'Captura leads' },
      { value: 'lead_qualification', label: 'Qualifica leads' },
      { value: 'online_booking', label: 'Permite agendamento' },
      { value: 'online_payment', label: 'Permite compra/pagamento' },
      { value: 'sends_to_crm', label: 'Envia dados para CRM' },
      { value: 'has_automation', label: 'Possui automações' },
      { value: 'unknown', label: 'Não sei' },
    ],
  },
  {
    key: 'ai_opportunity',
    step: 8,
    type: 'multiple',
    question: 'Onde você acredita que IA poderia ajudar?',
    description: 'Selecione as áreas de interesse ("Não faço ideia" é uma resposta 100% válida).',
    hasOther: true,
    otherPlaceholder: 'Outra área',
    options: [
      { value: 'support', label: 'Atendimento' },
      { value: 'sales', label: 'Vendas' },
      { value: 'marketing', label: 'Marketing' },
      { value: 'internal_org', label: 'Organização interna' },
      { value: 'content', label: 'Produção de conteúdo' },
      { value: 'data_analysis', label: 'Análise de dados' },
      { value: 'documents', label: 'Documentos' },
      { value: 'proposals', label: 'Propostas e orçamentos' },
      { value: 'reports', label: 'Relatórios' },
      { value: 'process_auto', label: 'Automação de processos' },
      { value: 'no_idea', label: 'Não faço ideia' },
      { value: 'other', label: 'Outro' },
    ],
  },
  {
    key: 'main_bottleneck',
    step: 9,
    type: 'textarea',
    question: 'Se você pudesse eliminar um único gargalo hoje, qual seria?',
    placeholder: 'Conte o processo, tarefa ou situação que mais está tomando tempo, gerando retrabalho ou fazendo oportunidades se perderem.',
    maxLength: 1000,
  },
  {
    key: 'urgency',
    step: 10,
    type: 'scale',
    question: 'Quanto isso está atrapalhando sua operação hoje?',
    description: 'Avalie o impacto atual desse desafio no seu dia a dia.',
    options: [
      { value: '1', label: '1 — Só quero entender melhor' },
      { value: '2', label: '2 — É um incômodo' },
      { value: '3', label: '3 — Já está atrapalhando' },
      { value: '4', label: '4 — Está custando tempo ou dinheiro' },
      { value: '5', label: '5 — Preciso resolver isso logo' },
    ],
  },
];
