import { config } from './site.config';
import { ContactLinks } from './contact-links';
export const publicPages = {
  '/servicos/sites': { title: 'Sites e sistemas para empresas de serviços', description: 'Sites institucionais, landing pages e sistemas sob medida. Entenda entregas, escopo e como começar seu projeto com a !AI.', intro: 'Uma presença digital que explica seu negócio e facilita o próximo contato.', sections: [
    ['O que podemos construir', 'Landing pages para uma oferta específica, sites institucionais, e-commerce e sistemas para processos do seu negócio. A proposta define páginas, recursos, conteúdo e integrações antes do desenvolvimento.'],
    ['O que muda entre os projetos', 'Uma landing page reúne uma oferta em uma página. Um site institucional organiza serviços, empresa e contato em páginas próprias. Área restrita, catálogo e integrações aumentam o escopo.'],
    ['Como a entrega acontece', 'Alinhamos objetivo, materiais necessários, etapas e critérios de aceite. A entrega inclui testes e orientação conforme a proposta. Domínio, hospedagem, manutenção e serviços externos são discriminados separadamente.'],
    ['Referências de investimento', 'Landing page simples a partir de R$ 1.490; site institucional básico a partir de R$ 2.490. Prazo e preço final dependem das entregas e integrações.'],
  ] },
  '/servicos/automacoes': { title: 'Automações e integrações para sua operação', description: 'Conecte sistemas e reduza tarefas manuais com automações, integrações e IA aplicada. Conheça a abordagem da !AI.', intro: 'Menos copiar e colar. Mais informação chegando ao lugar certo.', sections: [
    ['Onde começar', 'Mapeamos tarefas repetidas e pontos em que informações se perdem. Priorizamos um fluxo com objetivo e resultado observável antes de expandir.'],
    ['Exemplos de aplicação', 'Organizar contatos recebidos, lembrar acompanhamentos, conectar formulários ao CRM e consolidar informações para relatórios. Cada integração depende dos recursos e permissões dos sistemas envolvidos.'],
    ['IA quando ela ajuda', 'Assistentes, classificação de informações e apoio à análise entram no escopo quando fizerem sentido. Definimos limites e revisão humana para decisões que exigem responsabilidade.'],
    ['Escopo e custos', 'Integrações a partir de R$ 600 e automação simples a partir de R$ 800. Viabilidade, volume, APIs, manutenção e custos externos são avaliados na proposta.'],
  ] },
  '/crm': { title: '!AI CRM: contatos, funil e acompanhamento', description: 'Conheça os planos !AI CRM e os pontos a definir na implantação: equipe, suporte, integrações e custos adicionais.', intro: 'Seu comercial com memória: contatos organizados e oportunidades acompanhadas.', sections: [
    ['Essencial — R$ 697/mês', 'Centralização de contatos, funil comercial e tarefas de acompanhamento. Um ponto de partida para organizar o relacionamento comercial.'],
    ['Gestão — R$ 997/mês', 'Inclui os recursos do Essencial, organização da operação comercial e relatórios e indicadores de gestão.'],
    ['Automação — R$ 1.497/mês', 'Inclui os recursos de Gestão, fluxos automatizados definidos no escopo e integrações conforme viabilidade.'],
    ['O que precisa constar na proposta', 'Quantidade de usuários, canais, volume, migração, treinamento, suporte, implantação e integrações. Os valores mensais não incluem automaticamente APIs, WhatsApp, IA ou serviços de terceiros. A implantação é cobrada separadamente.'],
    ['Antes de contratar', 'Solicite uma apresentação do fluxo que sua equipe precisa usar. A conversa verifica a adequação da solução e esclarece recursos e limites antes de fechar o escopo.'],
  ] },
  '/clinicas': { title: 'Sites, CRM e automações para clínicas', description: 'Conecte presença digital, atendimento e acompanhamento de contatos da clínica. Conheça a abordagem de tecnologia da !AI.', intro: 'Da primeira mensagem ao próximo atendimento, sem informação perdida pelo caminho.', sections: [
    ['Encontrar e entrar em contato', 'Um site que explica os serviços e facilita o contato. O conteúdo deve apresentar informações reais da clínica e orientar o visitante com clareza.'],
    ['Organizar e acompanhar', 'Contatos organizados no CRM, tarefas de acompanhamento e integrações de agendamento quando houver viabilidade técnica. Não pressupomos compatibilidade com todos os sistemas.'],
    ['Definir limites antes de integrar', 'O projeto distingue relacionamento comercial de prontuário e atendimento clínico. Não envie dados médicos no diagnóstico inicial. Acesso, responsabilidades e tratamento de informações exigem definição específica para cada operação.'],
  ] },
} as const;
export function PublicPage({ path }: { path: keyof typeof publicPages }) {
  const page = publicPages[path];
  const message = encodeURIComponent(`Olá! Gostaria de conversar sobre ${page.title}.`);
  return <main className="wrap document-page"><a className="logo" href="/">!AI</a><nav className="document-nav" aria-label="Navegação da página"><a href="/">Início</a><a href="/crm">CRM</a><a href="/clinicas">Clínicas</a><a href="/digital-check">Diagnóstico gratuito</a></nav><p className="eyebrow">TECNOLOGIA COM PROPÓSITO</p><h1>{page.title}</h1><p className="document-intro">{page.intro}</p>{page.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}<div className="actions"><a className="button" href={`https://wa.me/${config.contact.whatsapp.replace(/\D/g, '')}?text=${message}`} target="_blank" rel="noopener noreferrer">Conversar sobre esta solução</a><a className="button outline" href="/digital-check">Fazer diagnóstico gratuito</a></div><ContactLinks /><a className="text-link" href="/privacidade">Privacidade</a></main>;
}
export function PrivacyPage() { return <main className="wrap document-page"><a className="logo" href="/">!AI</a><p className="eyebrow">PRIVACIDADE / ATUALIZADO EM 2 DE OUTUBRO DE 2026</p><h1>Privacidade e uso das informações</h1><section><h2>Contato responsável</h2><p>Este site apresenta a operação I Can’t Believe It’s AI. Para dúvidas ou pedidos de acesso, correção e exclusão de informações, fale com o responsável pelo canal <a href={`mailto:${config.contact.email}`}>{config.contact.email}</a>.</p></section><section><h2>O que você envia</h2><p>O formulário solicita nome, empresa, WhatsApp e desafio atual. E-mail e site ou Instagram são opcionais. As respostas descrevem sua rotina e prioridades. Não envie senhas, dados médicos ou informações sensíveis.</p></section><section><h2>Para que usamos</h2><p>As informações são usadas para preparar o diagnóstico inicial, organizar as respostas e entrar em contato sobre o contexto apresentado. O diagnóstico é indicativo e não substitui uma auditoria técnica completa. O envio não representa autorização para campanhas de publicidade.</p></section><section><h2>Sessão e armazenamento</h2><p>O navegador guarda temporariamente um identificador e uma chave para retomar o diagnóstico na mesma aba. Respostas enviadas são armazenadas pelo serviço de diagnóstico. Fechar a aba pode encerrar a retomada. Consulte o responsável para esclarecer retenção e solicitar exclusão.</p></section><section><h2>Links de contato</h2><p>WhatsApp, ligação e e-mail abrem serviços externos. A conversa segue pelas condições desses serviços. Nenhuma mensagem é enviada automaticamente pelo site.</p></section><section><h2>Se você não quiser preencher</h2><p>Você pode conversar pelos canais abaixo. Não é necessário iniciar o diagnóstico para pedir informações sobre um projeto.</p></section><ContactLinks /><a className="text-link" href="/">Voltar ao site</a></main>; }
