import ClientBrands from './client-brands';
import { ArrowIcon } from './arrow-icon';
import { config as c } from './site.config';
import { ContactLinks } from './contact-links';
import { ContactBriefing } from './contact-briefing';
function Section({id,light=false,children}:{id:string,light?:boolean,children:React.ReactNode}) { return <section id={id} className={'section '+(light?'light':'')}><div className="wrap">{children}</div></section>; }
const whatsapp = (topic: string) => `https://wa.me/${c.contact.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(`Olá! Gostaria de conversar sobre ${topic}.`)}`;
export default function Sections() { return <>
  <section className="check-banner"><div className="wrap split"><div><div className="eyebrow">UM BOM LUGAR PARA COMEÇAR</div><h2>Encontre o próximo passo.</h2></div><div><p>Conte como funciona seu atendimento e quais tarefas estão tomando seu tempo. Recebemos seu briefing para entender onde podemos ajudar.</p><p>Sem compromisso de contratação. A análise é feita pela !AI e os próximos passos são discutidos na consultoria.</p><a href="/digital-check" className="button dark-button">Enviar meu briefing <ArrowIcon /></a></div></div></section>
  <Section id="solucoes" light><div className="eyebrow">CLÍNICAS E EMPRESAS DE SERVIÇOS</div><div className="split"><div><h2>Da primeira mensagem ao próximo atendimento.</h2><a className="text-link" href="/clinicas">Conhecer soluções para clínicas <ArrowIcon /></a></div><div><p>Seu cliente encontra você, a equipe organiza o contato e a conversa pode virar agendamento. Conectamos essas etapas de acordo com a sua operação.</p><ul className="benefit-list"><li>Site que explica o serviço e facilita o contato.</li><li>CRM para organizar oportunidades e acompanhamentos.</li><li>Integrações viáveis com as ferramentas que você utiliza.</li></ul></div></div></Section>
  <Section id="crm"><div className="section-top"><div><div className="eyebrow">CONTATOS, FUNIL E ACOMPANHAMENTO</div><h2>Seu comercial com memória.</h2></div><a className="text-link" href="/crm">Conhecer o !AI CRM <ArrowIcon /></a></div><div className="steps">{[['Contatos organizados','Reúna as informações e acompanhe cada oportunidade no funil.'],['Próximos passos claros','Organize tarefas e acompanhamentos para dar continuidade às conversas.'],['Uma operação conectada','Defina relatórios, automações e integrações de acordo com a rotina da equipe.']].map(([title,desc],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="actions"><a className="button" href={whatsapp('uma consultoria para organizar meu CRM')} target="_blank" rel="noopener noreferrer">Conversar sobre meu CRM <ArrowIcon /></a></div></Section>
  <Section id="consultoria" light><div className="split"><div><div className="eyebrow">UMA PROPOSTA QUE FAZ SENTIDO PARA VOCÊ</div><h2>Primeiro, entendemos. Depois, propomos.</h2><p>A consultoria conecta o que sua operação precisa às soluções que podemos construir. Os valores são apresentados na conversa, com escopo e prioridades definidos.</p><a className="button dark-button" href={whatsapp('a consultoria para meu negócio')} target="_blank" rel="noopener noreferrer">Conversar sobre a consultoria <ArrowIcon /></a></div><div className="delivery-list"><h3>Entender sua rotina</h3><p>Conhecer seus objetivos, ferramentas e os pontos que estão travando a operação.</p><h3>Definir prioridades</h3><p>Escolher por onde começar e quais entregas terão mais utilidade para o seu negócio.</p><h3>Receber uma proposta sob medida</h3><p>Alinhar solução, etapas, prazo e investimento antes de iniciar o projeto.</p></div></div></Section>
  <Section id="entregas"><div className="eyebrow">COMO AVALIAR O PROJETO</div><div className="split"><div><h2>Saiba o que você vai receber.</h2><p className="subtle">Uma decisão segura começa com escopo, acompanhamento e critérios de entrega.</p></div><div className="delivery-list"><h3>Antes de começar</h3><p>Objetivo, entregas, prazo, investimento e responsabilidades na proposta.</p><h3>Durante o projeto</h3><p>Etapas de construção e acompanhamento para revisar o que está sendo feito.</p><h3>Na entrega</h3><p>Testes, orientação de uso e definição de suporte conforme o escopo contratado.</p></div></div></Section>
  <Section id="processo" light><div className="eyebrow">SEM CAIXA-PRETA</div><h2>Você acompanha cada passo.</h2><div className="steps">{[['Entendemos e diagnosticamos','Mapeamos sua rotina, gargalos e prioridades.'],['Definimos e construímos','Alinhamos escopo e investimento, com etapas de acompanhamento.'],['Entregamos e evoluímos','Testes, orientação e suporte conforme o escopo contratado.']].map(([title,desc],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></Section>
  <Section id="sobre" light><div className="about"><div className="mascot"><img src="/nex-standing-640.webp" srcSet="/nex-standing-320.webp 320w, /nex-standing-640.webp 640w" sizes="(max-width:760px) 80vw, 35vw" width="640" height="1147" alt="NEX, mascote da !AI: uma ema de óculos e moletom." loading="lazy"/><span>NEX / MASCOTE !AI</span></div><div><div className="eyebrow">I CAN’T BELIEVE IT’S AI</div><h2>Tecnologia com clareza.</h2><p>Somos uma operação independente de tecnologia. Construímos sites, sistemas e conexões para o seu negócio — com IA quando ela ajuda e boa engenharia sempre.</p><p>O NEX é nosso mascote. Quem atende sua solicitação é a operação !AI, pelos canais de contato abaixo.</p><ContactLinks /></div></div></Section>
  <ClientBrands />
  <Section id="faq" light><div className="split"><div><div className="eyebrow">ANTES DE CONVERSAR</div><h2>Respostas diretas.</h2></div><div className="faq">{c.faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></Section>
  <Section id="contato"><div className="split"><div><div className="eyebrow">ESCOLHA COMO COMEÇAR</div><h2>Vamos olhar para sua operação?</h2><p>Para orçamento ou dúvidas sobre CRM, fale diretamente. Se ainda não sabe por onde começar, envie seu briefing.</p><ContactLinks /></div><div><h3>Conte seu contexto</h3><p id="briefing-help">Preencha um breve contexto e um canal de contato. Vamos analisar sua solicitação e conversar sobre as prioridades.</p><ContactBriefing /></div></div></Section>
  <footer className="wrap footer"><div className="footer-top"><a className="wordmark" href="/">I can’t believe<br/>it’s AI<span>.</span></a><div><p>Tecnologia para negócios</p><p className="subtle">Uma operação independente.</p><a className="text-link" href="/digital-check">Enviar briefing</a></div><nav aria-label="Rodapé">{c.nav.map(([label,id])=><a key={id} href={'/#'+id}>{label}</a>)}<a href="/servicos/sites">Sites e sistemas</a><a href="/servicos/automacoes">Automações</a><a href="/privacidade">Privacidade</a></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} I Can’t Believe It’s AI</span><a href="#inicio">De volta ao topo <ArrowIcon direction="up" /></a><span>Feito para funcionar.</span></div></footer>
</>; }
