import { ArrowIcon } from './arrow-icon';

import {config as c} from './site.config';
import {Briefing} from './interactions';
function Section({id,light=false,children}:{id:string,light?:boolean,children:React.ReactNode}){return <section id={id} className={'section reveal '+(light?'light':'')}><div className="wrap">{children}</div></section>}
export default function Sections({ onStartCheck }: { onStartCheck?: (checkId: string, token: string, lead: { name: string; company: string; websiteOrInstagram?: string }) => void } = {}){return <>
<Section id="problemas"><div className="split"><div><div className="eyebrow">02 / O CUSTO DO “SEMPRE FOI ASSIM”</div><h2>Ainda<br/>fazendo isso?</h2><p className="subtle">Seu time tem coisas melhores para fazer.<br/>O copiar e colar pode pedir demissão.</p><a href="#contato" className="text-link">Quero tirar isso da minha rotina <ArrowIcon /></a></div><div className="problem-list">{['Copiando leads do WhatsApp para uma planilha.','Lembrando de cada follow-up de cabeça.','Digitando os mesmos dados em três sistemas.','Perdendo contatos em mensagens antigas.','Montando relatórios manualmente toda semana.'].map((p,i)=><div key={p}><span>0{i+1}</span><p>{p}</p><span aria-hidden="true"><ArrowIcon /></span></div>)}</div></div></Section>
<section className="check-banner"><div className="wrap split"><div><div className="eyebrow">UM BOM LUGAR PARA COMEÇAR</div><h2>!AI Digital Check<span><ArrowIcon /></span></h2></div><div><p>Um olhar de fora para encontrar o que pode funcionar melhor por dentro.</p><p>Analisamos sua presença digital, atendimento e tarefas manuais para indicar prioridades. Diagnóstico inicial gratuito, sem compromisso.</p><a href="#contato" className="button dark-button">Quero meu diagnóstico gratuito <ArrowIcon /></a></div></div></section>
<Section id="solucoes" light><div className="eyebrow">03 / CLÍNICAS & NEGÓCIOS DE SERVIÇOS</div><div className="split"><h2>Da primeira mensagem<br/>ao próximo atendimento.</h2><div><p>O cliente encontra você. A recepção recebe o contato. A conversa vira agendamento. E ninguém precisa caçar informação pelo caminho.</p><p className="muted">Conectamos presença digital, atendimento e gestão para a rotina fazer sentido de ponta a ponta.</p></div></div><div className="flow" aria-label="Jornada: encontrar, conversar, agendar e acompanhar">{[['01','Encontrar','Sites que explicam e convidam à ação.'],['02','Conversar','Contatos organizados no CRM.'],['03','Agendar','Integrações de acordo com sua operação.'],['04','Acompanhar','Follow-ups e visão do relacionamento.']].map(([n,t,d])=><div key={n}><span>{n} <ArrowIcon direction="right" /></span><h3>{t}</h3><p>{d}</p></div>)}</div><a className="text-link" href="#contato">Vamos olhar para sua operação <ArrowIcon /></a></Section>
<Section id="crm"><div className="section-top"><div><div className="eyebrow">04 / CONTATO NÃO É A MESMA COISA QUE RELACIONAMENTO</div><h2>!AI CRM<span className="lime">.</span></h2></div><p className="subtle">Seu comercial com memória.<br/>E você com uma visão do que vem depois.</p></div><div className="plans">{c.plans.map((p,i)=><article className={'plan '+(i===1?'featured':'')} key={p.name}><div className="eyebrow">{i===1?'PARA CONDUZIR A OPERAÇÃO':'0'+(i+1)+' / CRM'}</div><h3>{p.name}</h3><p>{p.description}</p><div className="price">{p.price}<small>/mês</small></div><ul>{p.features.map(f=><li key={f}><ArrowIcon /> {f}</li>)}</ul><a className={'button '+(i===1?'':'outline')} href="#contato">Conversar sobre o {p.name} <ArrowIcon /></a></article>)}</div><p className="fine">Implantação cobrada separadamente. Recursos e limites serão definidos na proposta. APIs, WhatsApp, IA e serviços de terceiros podem gerar custos adicionais.</p></Section>
<Section id="precos" light><div className="split"><div><div className="eyebrow">05 / SEM MISTÉRIO NO PRIMEIRO PASSO</div><h2>Tecnologia sob medida.<br/>Um ponto de partida<br/>bem claro.</h2><p className="muted">Preços a partir de. O investimento final depende do escopo, complexidade e integrações.</p><a href="#contato" className="text-link">Definir meu projeto <ArrowIcon /></a></div><div className="price-list">{c.prices.map(([name,price])=><div key={name}><span>{name}</span><strong>{price}</strong></div>)}</div></div></Section>
<Section id="cases"><div className="eyebrow">06 / O TRABALHO FALA</div><div className="section-top"><h2>Menos promessa.<br/>Mais coisa funcionando.</h2><p className="subtle">Os primeiros projetos estão ganhando<br/>seu espaço por aqui.</p></div><div className="cases">{c.cases.map((x,i)=><article key={x.label}><div className={'case-cover case-'+i}><span>{x.status}</span><strong>0{i+1}<sup><ArrowIcon /></sup></strong><small>CLÍNICAS / TECNOLOGIA</small></div><div className="case-copy"><span className="eyebrow">{x.label}</span><h3>{x.title}</h3><p>{x.description}</p></div></article>)}</div></Section>
<Section id="processo" light><div className="eyebrow">07 / SEM CAIXA-PRETA</div><h2>Você entende o caminho.<br/>E acompanha cada passo.</h2><div className="steps">{c.steps.map(([title,desc],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></Section>
<Section id="sobre" light><div className="about"><div className="mascot"><img src="/nex-standing-transparent.png" width="937" height="1679" alt="NEX, ema de plumagem creme, óculos pretos e moletom !AI, em pé com as mãos na cintura." loading="lazy"/><span>NEX / DIRETOR DE MENOS DO MESMO</span></div><div><div className="eyebrow">08 / WHY THE WEIRD NAME?</div><h2>A surpresa fica no nome.<br/>A clareza, no trabalho.</h2><p>“I Can’t Believe It’s AI” é aquela reação quando algo complicado finalmente fica simples. É esse o efeito que buscamos.</p><p>Somos uma operação independente de tecnologia. Construímos sites, sistemas e conexões que fazem sentido para o seu negócio — com IA quando ela ajuda, e com boa engenharia sempre.</p><p className="muted">O NEX, nossa ema de óculos, tem pouca paciência para trabalho repetido. A gente entende.</p><blockquote className="mascot-motto">“Durma enquanto as ferramentas trabalham.”<cite>— NEX</cite></blockquote><p className="signature">Tecnologia que parece mágica.<br/>Mas funciona de verdade.</p></div></div></Section>
<Section id="faq" light><div className="split"><div><div className="eyebrow">09 / ANTES DE CONVERSAR</div><h2>Boas perguntas.<br/>Respostas diretas.</h2></div><div className="faq">{c.faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></Section>
<Section id="contato"><div className="split"><div><div className="eyebrow">10 / WHAT’S ANNOYING YOU?</div><h2>O que está<br/>travando<br/>seu negócio?</h2><p className="lime large">Vamos resolver <ArrowIcon /></p><p className="subtle">Comece pelo !AI Digital Check.<br/>Conte o contexto. A gente ajuda a encontrar o próximo passo.</p></div><Briefing onStartCheck={onStartCheck}/></div></Section>
<footer className="wrap footer"><div className="footer-top"><a className="wordmark" href="#inicio">I can’t believe<br/>it’s AI<span>.</span></a><div><p>Tecnologia para negócios</p><p className="subtle">Uma operação independente.<br/>Parceira da V Company.</p></div><nav aria-label="Rodapé">{c.nav.map(([label,id])=><a key={id} href={'#'+id}>{label}</a>)}</nav></div><details id="privacidade"><summary>Privacidade e tratamento de dados</summary><p>Usamos as informações enviadas para preparar seu Digital Check e entrar em contato sobre o diagnóstico. Os dados são armazenados de forma segura e não são compartilhados com terceiros para fins de publicidade. Não envie senhas, dados médicos ou outras informações confidenciais. Para esclarecer dúvidas sobre o tratamento de dados ou solicitar exclusão, utilize o canal de contato configurado no site.</p></details><div className="footer-bottom"><span>© {new Date().getFullYear()} I Can’t Believe It’s AI</span><a href="#inicio">De volta ao topo ↑</a><span>Feito para funcionar.</span></div></footer></>}



