export const config={
contact:{email:'',whatsapp:''},
siteUrl:'https://icantbelieveitsai-beta.italopablo.chatgpt.site',
nav:[['Serviços','servicos'],['Soluções','solucoes'],['CRM','crm'],['Cases','cases'],['Como funciona','processo'],['Sobre','sobre']],
pillars:[['Build','Uma presença que abre portas. Sistemas que sustentam o próximo passo.','Sites / Landing pages / E-commerce / Sistemas'],['Automate','O trabalho repetitivo sai da sua agenda. E entra em um fluxo que funciona.','Automações / Integrações / APIs / Workflows'],['Intelligence','Inteligência artificial aplicada a problemas reais. Sem espetáculo vazio.','IA / Agentes / Assistentes / Análise'],['Operate','Colocar no ar é o começo. A operação precisa continuar funcionando.','CRM / Suporte / Manutenção / Monitoramento']],
prices:[['Landing page simples','R$ 1.490'],['Landing page premium','R$ 2.490+'],['Site institucional básico','R$ 2.490+'],['Site institucional intermediário','R$ 3.490–4.990'],['Site avançado','R$ 5.000+'],['Reformulação','R$ 1.990–4.990+'],['E-commerce','R$ 4.990+'],['Integrações','R$ 600+'],['Automação simples','R$ 800+'],['Automação intermediária','R$ 1.500–3.000'],['Hora técnica','R$ 120–150 / hora'],['Suporte','R$ 149 / R$ 249 / R$ 449+ por mês']],
plans:[{name:'Essencial',price:'R$ 697',description:'Organize os contatos. Enxergue as oportunidades.',features:['Centralização de contatos','Funil comercial','Tarefas e acompanhamento']},{name:'Gestão',price:'R$ 997',description:'Uma visão melhor para conduzir a equipe.',features:['Tudo do Essencial','Organização da operação comercial','Relatórios e indicadores de gestão']},{name:'Automação',price:'R$ 1.497',description:'Menos tarefas repetidas entre uma etapa e outra.',features:['Tudo do Gestão','Fluxos automatizados definidos no escopo','Integrações conforme viabilidade']}],
cases:[{label:'Clínica 01',title:'Uma jornada digital mais simples.',description:'Espaço reservado para contexto, solução e entregas após aprovação do cliente.',status:'Case em preparação'},{label:'Clínica 02',title:'Mais conexão. Menos tarefas soltas.',description:'Nome, imagens e resultados serão publicados com autorização do cliente.',status:'Case em preparação'}],
steps:[['Entendemos','O negócio, a rotina e o que está travando.'],['Diagnosticamos','Onde estão os gargalos e as oportunidades.'],['Definimos','Escopo, investimento e critérios de entrega.'],['Construímos','Com etapas claras e acompanhamento.'],['Colocamos no ar','Testes, ajustes e orientação para usar.'],['Evoluímos','Suporte e melhorias conforme o plano contratado.']],
faq:[['Vocês trabalham só com clínicas?','Não. Clínicas e negócios de serviços são um foco, mas atendemos empresas de outros segmentos quando existe um problema que podemos resolver bem.'],['Preciso saber exatamente o que contratar?','Não. O Digital Check ajuda a identificar prioridades. Depois, definimos uma proposta com escopo, prazo e investimento.'],['O Digital Check é mesmo gratuito?','Sim. É uma análise inicial do seu contexto, sem obrigação de contratação. Não inclui implementação nem auditoria técnica completa.'],['O que está incluído nos preços?','Os valores são referências iniciais. O orçamento final depende do escopo, conteúdo, integrações e complexidade. Domínio, hospedagem e serviços externos são discriminados na proposta.'],['O CRM tem custo de implantação?','Sim. A implantação é separada e depende da configuração, migração e treinamento. APIs, WhatsApp, IA e serviços de terceiros podem gerar custos adicionais.'],['Qual é o prazo de um projeto?','O prazo depende das entregas e dos materiais necessários. Você recebe um cronograma antes de começar.']]
};
